version: '3'
services:
  app:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    container_name: graphql-api
    ports: 
     - "8081:8081"
    environment: 
      - MOVIES_CSV_PATH=/app/archive/movies_metadata.csv
      - ACTORS_CSV_PATH=/app/archive/credits.csv
      - RATINGS_CSV_PATH=/app/archive/ratings.csv
      - DB_CONNECTION_STRING=mongodb://root:secret@mongo:27017/graphql-api-db?authSource=admin
      - DOCKER=true
    # env_file:
    #   - .env
    # volumes:
    #   - .:/app
    # restart: unless-stopped
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: graphql-api-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
      # - mongo-data:/data/db
      # - ./mongodb-seed:/dump
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  # api:
  #   build: .
  #   container_name: graphql-api
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     DB_CONNECTION_STRING: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/graphql-api-db?authSource=admin
  #   command: ./entrypoint.sh
  #   volumes:
  #     - .:/app
  #   restart: unless-stopped

volumes:
  mongo-data:
  