# Defines the movie GraphQL schema.
# Author: Beatriz Sanssi

type Movie {
  _id: ID!
  id: Int!
  title: String!
  release_date: Int!
  genre: String!
  description: String!
  actors: [Actor]
  ratings: [Rating]
  averageRating: Float

}

type DeleteMovieResponse {
  deletedMovie: Movie
  message: String
}

extend type Query {
  movies(genre: String, year: Int, id: Int): [Movie]
  movie(id: Int!): Movie
}

extend type Mutation {
  addMovie(id: Int! title: String!, release_date: Int!, genre: String!, description: String!): Movie
  updateMovie(id: ID!, title: String, release_date: Int, genre: String, description: String): Movie
  deleteMovie(id: ID!): DeleteMovieResponse
}