# Defines the movie GraphQL schema.
# Author: Beatriz Sanssi

type Movie {
  _id: ID!
  id: Int!
  title: String!
  release_date: Int!
  genre: String!
  description: String!
  ratings: [Rating]
  averageRating: Float

}

extend type Query {
  movies(id: Int, genre: String, year: Int): [Movie]
  movie(id: Int!): Movie
}

extend type Mutation {
  addMovie(title: String!, release_date: Int!, genre: String!, description: String!): Movie
  updateMovie(id: ID!, title: String, release_date: Int, genre: String, description: String): Movie
  deleteMovie(id: ID!): Movie
}